# spring:
#   main:
#     web-application-type: none

server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: spring
  http2:
    enabled: true
